resources:
  - name: execTemplatesGit
    type: GitRepo
    configuration:
      path: rahulnlb1/tryout-extension
      gitProvider: Github
      branches:
        include: ^{{gitBranch}}$
      files:
        include: \bexecTemplates\/.+\b
  - name: res5
    type: testing/SampleResource
    configuration:
      foo: Hello
      sourceArtifactory: pipeArt
      # gitProvider: Github

pipelines:
 - name: sleep_pipeline_extension
   steps:
      - name: S_Bash_0023
        type: shippable/HealthCheck
        configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           integrations:
            - name: Slack
           inputResources:
            - name: execTemplatesGit
            - name: res5
