resources:
  - name: execTemplatesGit
    type: GitRepo
    configuration:
      path: rahulnlb1/tryout-extension
      gitProvider: RahulGithub
      branches:
        include: ^{{gitBranch}}$
      files:
        include: \bexecTemplates\/.+\b

pipelines:
 - name: sleep_pipeline_extension
   configuration:
        nodePool: windows-master
   steps:
     - name: S_Bash_0023
       type: shippable/HealthCheck
       syntaxversion: 1.0.14
       configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           stuff:
              - "hi"
              - "hello"
           integrations:
            - name: Slack
           inputResources:
            - name: execTemplatesGit
