resources:
  - name: execTemplatesGit
    type: GitRepo
    configuration:
      path: rahulnlb1/tryout-extension
      gitProvider: rahuljGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
 - name: sleep_pipeline_extension
   steps:
      - name: S_Bash_0023
        type: Bash
        configuration:
          inputResources:
              - name: execTemplatesGit
        execution:
          onExecute:
            - echo "hello ${WORLD}" 
