resources:
  - name: execTemplatesGit
    type: GitRepo
    configuration:
      path: rahulnlb1/tryout-extension
      gitProvider: Github
      branches:
        include: ^{{gitBranch}}$
      files:
        include: \bexecTemplates\/.+\b
  - name: testResource
    type: testing/SampleResource
    configuration:
      foo: bar

pipelines:
 - name: sleep_pipeline_extension
   #configuration:
   #     nodePool: windows-master
   steps:
      - name: S_Bash_0023
        type: shippable/HealthCheck
        syntaxversion: 1.0.16
        configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           stuff:
              - "hi"
              - "hello"
           integrations:
            - name: Slack
           inputResources:
            - name: execTemplatesGit
            - name: testResource
