resources:
  - name: res1
    type: testing/SampleResource
    configuration:
      foo: Hello
      sourceArtifactory: art
      gitProvider: Github

  - name: res2
    type: GitRepo
    configuration:
      path: rahulnlb1/tryout-extension
      gitProvider: Github
      branches:
        include: ^{{gitBranch}}$
      files:
        include: \bexecTemplates\/.+\b
      

pipelines:
 - name: sleep_pipeline_extension
   #configuration:
   #     nodePool: windows-master
   steps:
      - name: S_Bash_0023
        type: shippable/HealthCheck
        configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           stuff:
              - "hi"
              - "hello"
           integrations:
            - name: Slack
           inputResources:
            - name: res1
            - name: res2
