resources:
  - name: execTemplatesGit
    type: GitRepo
    configuration:
      path: rahulnlb1/tryout-extension
      gitProvider: Github
      branches:
        include: ^{{gitBranch}}$
      files:
        include: \bexecTemplates\/.+\b
  - name: res1
    type: SampleResource
    syntaxVersion: 0.0.3
    configuration:
      foo: bar

pipelines:
 - name: sleep_pipeline_extension
   steps:
      - name: S_Bash_0023
        type: HealthCheck
        syntaxVersion: 0.0.3
        configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           stuff:
              - "hi"
              - "hello"
           integrations:
            - name: Slack
           inputResources:
            - name: execTemplatesGit
            - name: res1
